#!/usr/bin/env node
// prototype.js — turn a figo2godot-exported project (one .tscn per captured UI
// state) into a clickable interaction prototype. Given a nav graph (scene ->
// [{text|auto, to}]) derived from the source app's logic, it:
//   - writes NavData.gd (the graph) + Screen.gd (the wiring) into the project,
//   - attaches Screen.gd to every screen .tscn root,
//   - registers NavData as an autoload and sets the main scene.
// Screen.gd finds a trigger by its VISIBLE text (web2canvas doesn't export the
// DOM title attr, so icon-only buttons can't be matched) and lays a transparent
// Button over it that changes scene. `auto` makes a timed transition (role ->
// game). Run AFTER --prefabs/import; re-run is idempotent.
//
//   node prototype.js <godotDir> <nav.json>
const fs = require('fs');
const path = require('path');

const dir = process.argv[2], navPath = process.argv[3];
if (!dir || !navPath) { console.error('usage: prototype.js <godotDir> <nav.json>'); process.exit(2); }
const nav = JSON.parse(fs.readFileSync(navPath, 'utf8'));
const main = nav.main || 'lobby';

// ---- NavData.gd : the interaction graph as a GDScript dictionary -------------
fs.writeFileSync(path.join(dir, 'NavData.gd'),
  'extends Node\n# Auto-generated by prototype.js. scene name -> list of transitions.\n' +
  'var GRAPH := ' + JSON.stringify(nav.graph, null, 1).replace(/\n/g, '\n') + '\n');

// ---- Screen.gd : wire each scene's triggers to scene changes -----------------
fs.writeFileSync(path.join(dir, 'Screen.gd'), `extends Control
# Auto-generated by prototype.js. Attached to every screen root.
func _ready() -> void:
	await get_tree().process_frame
	await get_tree().process_frame
	var key := scene_file_path.get_file().get_basename()
	var trans: Array = NavData.GRAPH.get(key, [])
	var all_texts: Array = []
	for e in trans:
		if not e.has("auto"): all_texts.append(String(e["text"]))
	for e in trans:
		if e.has("auto"):
			var t := get_tree().create_timer(float(e["auto"]))
			t.timeout.connect(func(): _go(e["to"]))
			continue
		var n := _find(self, String(e["text"]))
		if n == null: continue
		var r: Rect2 = _click_target(n, all_texts, String(e["text"]))
		if r.size.x < 1.0 or r.size.y < 1.0: continue
		var b := Button.new()
		b.flat = true
		b.focus_mode = Control.FOCUS_NONE
		b.modulate = Color(1, 1, 1, 0)
		b.position = r.position
		b.size = r.size
		var to: String = e["to"]
		b.pressed.connect(func(): _go(to))
		add_child(b)

func _go(scene: String) -> void:
	get_tree().change_scene_to_file("res://%s.tscn" % scene)

# The matched Label is just the text; the clickable region is its button/row
# ancestor. Grow the target up the tree but STOP before an ancestor that also
# contains another trigger's text (that ancestor is a multi-button container,
# e.g. the lobby menu column) — so each button gets its own hit area.
func _click_target(node: Node, all_texts: Array, my_text: String) -> Rect2:
	var screen := get_viewport_rect().size
	var screen_area := screen.x * screen.y
	var best: Rect2 = (node as Control).get_global_rect()
	var cur: Node = node.get_parent()
	for i in range(6):
		if cur == null or cur == self or not (cur is Control): break
		var has_other := false
		for t in all_texts:
			if t != my_text and _find(cur, t) != null:
				has_other = true
				break
		if has_other: break
		var rr: Rect2 = (cur as Control).get_global_rect()
		if rr.size.x * rr.size.y < screen_area * 0.5:
			best = rr
		cur = cur.get_parent()
	return best

func _find(node: Node, txt: String) -> Node:
	if node is Label and (node as Label).text.findn(txt) != -1:
		return node
	for c in node.get_children():
		var r := _find(c, txt)
		if r != null:
			return r
	return null
`);

// ---- attach Screen.gd to each screen .tscn root -----------------------------
const SCR_ID = 'scr_screen';
let wired = 0;
for (const f of fs.readdirSync(dir)) {
  if (!f.endsWith('.tscn')) continue;
  const p = path.join(dir, f);
  let s = fs.readFileSync(p, 'utf8');
  if (s.includes('res://Screen.gd')) continue;            // idempotent
  // bump load_steps and inject the Script ext_resource after the header
  s = s.replace(/\[gd_scene([^\]]*?)load_steps=(\d+)([^\]]*)\]/,
    (m, a, n, b) => `[gd_scene${a}load_steps=${+n + 1}${b}]\n[ext_resource type="Script" path="res://Screen.gd" id="${SCR_ID}"]`);
  if (!s.includes(SCR_ID)) {  // no load_steps (shouldn't happen) — add after first line
    s = s.replace(/(\[gd_scene[^\]]*\]\n)/, `$1[ext_resource type="Script" path="res://Screen.gd" id="${SCR_ID}"]\n`);
  }
  // add `script=` to the ROOT node (first [node ...] line without a parent=)
  s = s.replace(/(\n\[node name="[^"]*" type="[^"]*"\]\n)/, (m) =>
    m.endsWith('\n') ? m + `script = ExtResource("${SCR_ID}")\n` : m);
  fs.writeFileSync(p, s);
  wired++;
}

// ---- project.godot : autoload + main scene ----------------------------------
const pg = path.join(dir, 'project.godot');
let g = fs.readFileSync(pg, 'utf8');
if (!g.includes('[autoload]')) g += `\n[autoload]\n\nNavData="*res://NavData.gd"\n`;
else if (!g.includes('NavData=')) g = g.replace('[autoload]\n', '[autoload]\n\nNavData="*res://NavData.gd"\n');
if (/run\/main_scene=/.test(g)) g = g.replace(/run\/main_scene=.*/,'run/main_scene="res://' + main + '.tscn"');
else g = g.replace(/\[application\]\n/, `[application]\n\nrun/main_scene="res://${main}.tscn"\n`);
fs.writeFileSync(pg, g);

console.log(`prototype: wired ${wired} scene(s), main = ${main}.tscn`);
